# permissions for end users to view benchinstallations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: benchinstallation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bench-operator
    app.kubernetes.io/part-of: bench-operator
    app.kubernetes.io/managed-by: kustomize
  name: benchinstallation-viewer-role
rules:
  - apiGroups:
      - bench.ravianand.me
    resources:
      - benchinstallations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - bench.ravianand.me
    resources:
      - benchinstallations/status
    verbs:
      - get
